git remote add elizaveta-andreeva https://github.com/elizaveta-andreeva/spbetu_comparch_2022_1303.git # Андреева Елизавета    
git remote add DaniiLBez          https://github.com/DaniiLBez/spbetu_comparch_2022_1303.git          # Беззубов Даниил       
git remote add feyhoa             https://github.com/feyhoa/spbetu_comparch_2022_1303.git             # Бутыло Егор           
git remote add Corvussharp        https://github.com/Corvussharp/spbetu_comparch_2022_1303.git        # Герасименко Ярослав   
git remote add Ghost-hk           https://github.com/Ghost-hk/spbetu_comparch_2022_1303.git           # Дауди Ибрагим         
git remote add Illy-GIS           https://github.com/Illy-GIS/spbetu_comparch_2022_1303.git           # Жилин Илья            
git remote add Arthur410          https://github.com/Arthur410/spbetu_comparch_2022_1303.git          # Иванов Артур          
git remote add Popug-s-catcher    https://github.com/Popug-s-catcher/spbetu_comparch_2022_1303.git    # Иевлев Егор           
git remote add obsessedwithmoney  https://github.com/obsessedwithmoney/spbetu_comparch_2022_1303.git  # Карагезов Савелий     
git remote add Pac1fik            https://github.com/Pac1fik/spbetu_comparch_2022_1303.git            # Кольцов Алексей       
git remote add Ajems              https://github.com/Ajems/spbetu_comparch_2022_1303.git              # Коренев Данил         
git remote add korenoff           https://github.com/korenoff/spbetu_comparch_2022_1303.git           # Коренченко Иван       
git remote add polinaKoroleva05   https://github.com/polinaKoroleva05/spbetu_comparch_2022_1303.git   # Королева Полина       
git remote add NikKropotov        https://github.com/NikKropotov/spbetu_comparch_2022_1303.git        # Кропотов Никита       
git remote add KuznetsovNick      https://github.com/KuznetsovNick/spbetu_comparch_2022_1303.git      # Кузнецов Николай      
git remote add Yulia2222          https://github.com/Yulia2222/spbetu_comparch_2022_1303.git          # Куклина Юлия          
git remote add Lifeestyleee       https://github.com/Lifeestyleee/spbetu_comparch_2022_1303.git       # Мусатов Дмитрий       
git remote add YaroslavNasonov    https://github.com/YaroslavNasonov/nasonov.git                      # Насонов Ярослав       
git remote add Alikohd            https://github.com/Alikohd/spbetu_comparch_2022_1303.git            # Попандопуло Александр 
git remote add KirillSamokhin     https://github.com/KirillSamokhin/spbetu_comparch_2022_1303.git     # Самохин Кирилл        
git remote add Sevazx129          https://github.com/Sevazx129/spbetu_comparch_2022_1303.git          # Смирнов Всеволод      
git remote add SyrtcevaDaria      https://github.com/SyrtcevaDaria/spbetu_comparch_2022_1303.git      # Сырцева Дарья         
git remote add TokGrin            https://github.com/TokGrin/spbetu_comparch_2022_1303.git            # Токун Григорий        
git remote add AlinaMoon123       https://github.com/AlinaMoon123/spbetu_comparch_2022_1303.git       # Хабибуллина Алина     
git remote add Olesya-Khulap      https://github.com/Olesya-Khulap/spbetu_comparch_2022_1303.git      # Хулап Олеся           
git remote add homin12            https://github.com/homin12/spbetu_comparch_2022_1303.git            # Чернуха Владимир      
git remote add defrozentruth      https://github.com/defrozentruth/spbetu_comparch_2022_1303.git      # Чубан Дмитрий         
git remote add Purposelessness    https://github.com/Purposelessness/spbetu_comparch_2022_1303.git    # Ягодаров Михаил       
